AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  S3BucketName:
    Type: String
    Description: "The name of the S3 bucket for hosting the Vue app."

  CloudFrontDistributionId:
    Type: String
    Description: "CloudFront distribution ID for cache invalidation."

Resources:
  VueS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref VueS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${VueS3Bucket}/*"

Outputs:
  WebsiteURL:
    Description: "S3 Static Website URL"
    Value: !Sub "http://${VueS3Bucket}.s3-website-${AWS::Region}.amazonaws.com/"
