name: Deploy Vue App to AWS

on:
  push:
    branches:
      - develop  # Runs when changes are pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name VueAppStack \
            --template-file cloudformation/cloudformation.yaml \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Vue App
        run: npm run build

      - name: Get CloudFormation Outputs
        id: get-outputs
        run: |
          S3_BUCKET=$(aws cloudformation describe-stacks --stack-name VueAppStack --query "Stacks[0].Outputs[?OutputKey=='S3BucketName'].OutputValue" --output text)
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name VueAppStack --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" --output text)
          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV
          echo "DISTRIBUTION_ID=$DISTRIBUTION_ID" >> $GITHUB_ENV

      - name: Deploy Vue App to S3
        run: |
          aws s3 sync dist/ s3://$S3_BUCKET --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
